### ISSUE TITLE
画像軽量化

### ISSUE THREAD

**Issue by sakukei** [sakukei/rite#161]
【課題】
・描画が遅い

【打ち手】
・プラグインでの圧縮、OR、アイキャッチ画像の軽量化など

**Comment by sakukei** [comment]
高島くん一緒に調べてもらえれば！

**Comment by parkercatz** [comment]
条件あるけど良さげなような
https://webllica.com/image-compression-plugin-for-wordpress/

**Comment by sakukei** [comment]
入れてもらいたいです！
