### ISSUE TITLE
0004_0005 検索結果もっとみるボタンの表示

### ISSUE THREAD

**Issue by sakukei** [sakukei/rite#7]
検索結果ページへのもっとみるボタンの表示
プラグイン前提でもOK

10件表示ずつ追加表示

**Comment by sakukei** [comment]
15件ずつに変更
https://extrip.atlassian.net/wiki/spaces/SPC/pages/126582870/0004+0005

工数見立て3-4ｈ

**Comment by takashima-dream-v** [comment]
ページャーがあるため実装なし
